CREATE TABLE resume1content(
    id varchar(30),
    name varchar(30),
    email varchar(30),
    number varchar(20),
    obj varchar(250),
    mdegc varchar(50),
    mbranch varchar(20),
    myear varchar(10),
    muniv varchar(30),
    maggr varchar(10),
    bachdegco varchar(20),
    bbranch varchar(20),
    byear varchar(10),
    buniv varchar(30),
    baggr varchar(10),
    iod varchar(10),
    iodcoll varchar(20),
    iodboard varchar(20),
    iodbranch varchar(20),
    iodyear varchar(10),
    iodaggr varchar(10),
    ssc varchar(20),
    syear varchar(10),
    sboard varchar(20),
    saggr varchar(10),
    projecttitle varchar(30),
    projectduration varchar(20),
    projectdescr varchar(250),
    training varchar(250),
    proglang varchar(50),
    scripting varchar(50),
    dbms varchar(50),
    os varchar(50),
    aa varchar(250),
    eca varchar(250),
    aof varchar(250),
    namessc varchar(50),
    fname varchar(50),
    dob varchar(20),
    paddr varchar(250),
    villnam varchar(30),
    decl varchar(250) );
    
    
    
    
    
    
    